### ISSUE TITLE
Glean dictionary is out of sync with this repo

### ISSUE THREAD

**Issue by rebecca-burwei** [mozilla/glean-annotations#191]
Here's what I currently see on the Glean dictionary at this [url](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/urlbar_engagement): 
<img width="1493" alt="image" src="https://github.com/mozilla/glean-annotations/assets/13172162/4fd83587-3475-4a95-a23d-178d385d2070">

Here is how the the repo's docs look at the latest commit on main: https://github.com/mozilla/glean-annotations/commit/d11db7f095a0c73e748b27dba86e000087091cb6

**Comment by badboy** [comment]
> Data last updated on [Friday, July 14, 2023](https://protosaur.dev/mps-deploys/). Built from revision [f9624621d3](https://github.com/mozilla/glean-dictionary/tree/f9624621d375763b935e7a776a1438c632475bbb).

Indeed somehow the Dictionary didn't deploy since then. I'll check.

**Comment by badboy** [comment]
Sorry, didn't mean to close this.

It didn't deploy since then because of [Bug 1843890](https://bugzilla.mozilla.org/show_bug.cgi?id=1843890): lookml_generator_staging failing since 2023-07-17, which is a prerequisite for glean-dictionary.

**Comment by badboy** [comment]
The dictionary is now redeployed with up-to-date info from 2023-07-20 at least.
